CREATE FUNCTION getNthHighestSalary(N INT) RETURNS INT
BEGIN
-- SET N = N-1;
  RETURN (
    -- SELECT DISTINCT(salary) from Employee order by salary DESC
    -- LIMIT 1 OFFSET N
SELECT SALARY FROM (SELECT SALARY, DENSE_RANK() OVER (ORDER BY SALARY DESC)AS RANKING FROM EMPLOYEE) AS RANKED_SALARIES
WHERE RANKING = N
LIMIT 1
  );
END;